version: 0.0
os: linux
files:
  - source: /
    destination: /var/html/www/unisolve-fe
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file