version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --force
  build:
     commands:
      - npm run build:development
  post_build:
    commands:
      - echo Build completed on `date`
   
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/node_modules/**/*'
